name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rust
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rust
      - run: cargo check --all-features --all-targets

  check-no-defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rust
      - run: cargo check --no-default-features --all-targets

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rust
      - run: rustup component add clippy
      - run: cargo clippy --all-features --all-targets -- -D warnings

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rust
      - run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rust
      - run: cargo test --all-features

  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rust
      - run: cargo test --all-features --doc
